
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Archivos;

import java_cup.runtime.*;
import Estructuras.Cola;
import Estructuras.MatrizDispersa;
import Main.Controlador;
import Nodos.NodoMatriz;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserImagen extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symImagen.class;
}

  /** Default constructor. */
  @Deprecated
  public parserImagen() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserImagen(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserImagen(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\006\000\002\003\003\000\002\004\004" +
    "\000\002\004\003\000\002\005\004\000\002\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\010\002\uffff\003\uffff\007\uffff\001\002\000" +
    "\010\002\010\003\007\007\005\001\002\000\004\004\011" +
    "\001\002\000\010\002\000\003\000\007\000\001\002\000" +
    "\010\002\ufffd\003\ufffd\007\ufffd\001\002\000\004\002\001" +
    "\001\002\000\004\007\012\001\002\000\010\003\ufffb\005" +
    "\ufffb\006\ufffb\001\002\000\010\003\016\005\014\006\015" +
    "\001\002\000\010\002\ufffe\003\ufffe\007\ufffe\001\002\000" +
    "\004\007\020\001\002\000\010\003\ufff9\005\ufff9\006\ufff9" +
    "\001\002\000\010\003\ufffc\005\ufffc\006\ufffc\001\002\000" +
    "\010\003\ufffa\005\ufffa\006\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\004\002\003\001\001\000\004\003\005\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\012\001\001\000\002\001" +
    "\001\000\004\005\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserImagen$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserImagen$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserImagen$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	List<Integer> lista = new ArrayList<>();
	public parserImagen(LexerImg lex) {
        super(lex);
    }		 


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserImagen$actions {
  private final parserImagen parser;

  /** Constructor */
  CUP$parserImagen$actions(parserImagen parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserImagen$do_action_part00000000(
    int                        CUP$parserImagen$act_num,
    java_cup.runtime.lr_parser CUP$parserImagen$parser,
    java.util.Stack            CUP$parserImagen$stack,
    int                        CUP$parserImagen$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserImagen$result;

      /* select the action based on the action number */
      switch (CUP$parserImagen$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)).value;
		RESULT = start_val;
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserImagen$parser.done_parsing();
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= INICIO SENTENCIA 
            {
              Object RESULT =null;

              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= 
            {
              Object RESULT =null;

              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // SENTENCIA ::= Numero Llave_a IMAGEN Llave_c 
            {
              Object RESULT =null;
		int D1left = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-3)).left;
		int D1right = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-3)).right;
		Token D1 = (Token)((java_cup.runtime.Symbol) CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-3)).value;
		Controlador.insertarImagen(D1.getLexeme(),lista); 
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-3)), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= error 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parserImagen$stack.peek()).value;
		  
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // IMAGEN ::= IMAGEN LINEA 
            {
              Object RESULT =null;

              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("IMAGEN",2, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // IMAGEN ::= Numero 
            {
              Object RESULT =null;
		int D2left = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).left;
		int D2right = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).right;
		Token D2 = (Token)((java_cup.runtime.Symbol) CUP$parserImagen$stack.peek()).value;
		 lista = new ArrayList<>();lista.add(Integer.parseInt(D2.getLexeme())); 
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("IMAGEN",2, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // LINEA ::= Coma Numero 
            {
              Object RESULT =null;
		int D3left = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).left;
		int D3right = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).right;
		Token D3 = (Token)((java_cup.runtime.Symbol) CUP$parserImagen$stack.peek()).value;
		 lista.add(Integer.parseInt(D3.getLexeme())); 
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("LINEA",3, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.elementAt(CUP$parserImagen$top-1)), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // LINEA ::= error 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parserImagen$stack.peek()).value;
		  
              CUP$parserImagen$result = parser.getSymbolFactory().newSymbol("LINEA",3, ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserImagen$stack.peek()), RESULT);
            }
          return CUP$parserImagen$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserImagen$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserImagen$do_action(
    int                        CUP$parserImagen$act_num,
    java_cup.runtime.lr_parser CUP$parserImagen$parser,
    java.util.Stack            CUP$parserImagen$stack,
    int                        CUP$parserImagen$top)
    throws java.lang.Exception
    {
              return CUP$parserImagen$do_action_part00000000(
                               CUP$parserImagen$act_num,
                               CUP$parserImagen$parser,
                               CUP$parserImagen$stack,
                               CUP$parserImagen$top);
    }
}

}
