
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 26 19:06:54 CST 2019
//----------------------------------------------------

package Archivos;

/** CUP generated class containing symbol constants. */
public class symCapas {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int COMA = 5;
  public static final int PUNTOYCOMA = 4;
  public static final int HEXA = 7;
  public static final int error = 1;
  public static final int LLAVECERRADA = 3;
  public static final int LLAVEABIERTA = 2;
  public static final int EOF = 0;
}

