
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Archivos;

/** CUP generated class containing symbol constants. */
public class symCapas {
  /* terminals */
  public static final int Color = 7;
  public static final int Error = 8;
  public static final int EOF = 0;
  public static final int Coma = 4;
  public static final int Llave_c = 3;
  public static final int PuntoComa = 5;
  public static final int error = 1;
  public static final int Llave_a = 2;
  public static final int Numero = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Llave_a",
  "Llave_c",
  "Coma",
  "PuntoComa",
  "Numero",
  "Color",
  "Error"
  };
}

