
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Archivos;

/** CUP generated class containing symbol constants. */
public class symUsuario {
  /* terminals */
  public static final int ID = 6;
  public static final int Numero = 5;
  public static final int Coma = 3;
  public static final int error = 1;
  public static final int DosPuntos = 2;
  public static final int PuntoComa = 4;
  public static final int Error = 7;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DosPuntos",
  "Coma",
  "PuntoComa",
  "Numero",
  "ID",
  "Error"
  };
}

